# Site
title:              Ben Rhine
bio:                'Leader / Developer / Tinkerer / DJ / Streamer / Geek'
description:        "Ben is a seasoned polyglot developer and development team lead with more than a decade of experience under his belt. He has worked across the board from small startups to multiple Fortune 100 companies. He specializes in Java and Groovy on Grails development with excelent Javascript skills across several major frameworks."
locale:             en_US
baseurl:            "" # the subpath of your site, e.g. /blog
url:                "https://benrhine.com" # the base hostname & protocol for your site
blog-header:        "Whats on my mind?"
blog-description:   "This could be anything from tech tutorials and intertesting technologies to my thoughts on politics and religion and whatever may be on mind."
blog-content-one:   ""
blog-content-two:   ""
tab-title-one:      "Home"
tab-title-two:      "About"
tab-title-three:    "Blog"
tab-title-four:     "Music"
tab-title-five:     "Projects"
tab-title-six:      "Consulting"
featured:    "Bring me on for your next project"
featured-description: ""

# Comments
disqus_shortname:   default

# Social
analytics-id:       "default"
twitter:            benrhine
facebook:           default
instagram:          default
github:             benrhine
linkedin:           benrhine

# personal
location:           Denver, CO
phone:              614-545-8725
email:              rhine.ben@gmail.com # change this to your email to receive free emails for your contact submissions via Slapform.com

# Other
background_image:   /images/bg.jpg
# Tip: The color palette and other styles can be configured in /_sass/lib/_vars.scss
slapform_thankyou_page: /thank-you

defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: post
    author:

# Jekyll
permalink:          /blog/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Gems
plugins:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

paginate: 6
paginate_path: "/blog/page:num/"

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]
